name: swisslandstats
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - swisslandstats-geopy
  - geopandas
  - osmnx>=1

  # linting/testing
  - black
  - bump2version
  - coverage
  - coveralls
  - isort
  - flake8
  - flake8-docstrings
  - pre-commit
  - pydocstyle
  - pytest
  - sphinx
